/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.tables.AccountsPayableTable;
import javax.swing.WindowConstants;

/**
 *
 * @author jaspertomas
 */
public class FrmAccountsPayable extends javax.swing.JFrame {

    private static FrmAccountsPayable instance;
    public static FrmAccountsPayable getInstance()
    {
        return instance;
    }
    
    
    /**
     * Creates new form FrmAccountsPayable
     */
    public FrmAccountsPayable() {
        initComponents();
        instance=this;
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        lblPage.setText(String.valueOf(table.getPage()+1));
        //table.gotoPage(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmdExit = new javax.swing.JButton();
        cmdFirstPage = new javax.swing.JButton();
        cmdPreviousPage = new javax.swing.JButton();
        cmdNextPage = new javax.swing.JButton();
        cmdLastPage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblPage = new javax.swing.JLabel();
        cmdRefresh = new javax.swing.JButton();
        table = new gui.tables.AccountsPayableTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("TMC Program: Accounts Payable");

        cmdExit.setText("Exit");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });

        cmdFirstPage.setText("First Page");
        cmdFirstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFirstPageActionPerformed(evt);
            }
        });

        cmdPreviousPage.setText("Previous Page");
        cmdPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPreviousPageActionPerformed(evt);
            }
        });

        cmdNextPage.setText("Next Page");
        cmdNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNextPageActionPerformed(evt);
            }
        });

        cmdLastPage.setText("Last Page");
        cmdLastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLastPageActionPerformed(evt);
            }
        });

        jLabel2.setText("Page ");

        lblPage.setText("0");

        cmdRefresh.setText("Refresh");
        cmdRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRefreshActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(cmdFirstPage)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmdPreviousPage)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblPage)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmdNextPage)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmdLastPage)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmdRefresh)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 271, Short.MAX_VALUE)
                        .add(cmdExit))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(table, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(table, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cmdExit)
                    .add(cmdFirstPage)
                    .add(cmdPreviousPage)
                    .add(cmdNextPage)
                    .add(cmdLastPage)
                    .add(jLabel2)
                    .add(lblPage)
                    .add(cmdRefresh))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        setVisible(false);
        FormManager.getInstance().getFrmMain().setVisible(true);
    }//GEN-LAST:event_cmdExitActionPerformed

    public void updatePageLabel()
    {
        lblPage.setText(String.valueOf(table.getPage()+1));
    }
    private void cmdFirstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFirstPageActionPerformed
//        if(table.getPage()!=0)
        {
            table.gotoPage(0);
            updatePageLabel();
        }
    }//GEN-LAST:event_cmdFirstPageActionPerformed

    private void cmdPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPreviousPageActionPerformed
        if(table.getPage()!=0)
        {
            table.gotoPage(table.getPage()-1);
            updatePageLabel();
        }
    }//GEN-LAST:event_cmdPreviousPageActionPerformed

    private void cmdNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNextPageActionPerformed
        if(table.getPage()!=table.getMaxPages()-1)
        {
            table.gotoPage(table.getPage()+1);
            updatePageLabel();
        }
    }//GEN-LAST:event_cmdNextPageActionPerformed

    private void cmdLastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLastPageActionPerformed
        if(table.getPage()!=table.getMaxPages()-1)
        {
            table.gotoPage(table.getMaxPages()-1);
            updatePageLabel();
        }
    }//GEN-LAST:event_cmdLastPageActionPerformed

    private void cmdRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRefreshActionPerformed
        table.gotoPage(table.getPage());
        lblPage.setText(String.valueOf(table.getPage()+1));
    }//GEN-LAST:event_cmdRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdFirstPage;
    private javax.swing.JButton cmdLastPage;
    private javax.swing.JButton cmdNextPage;
    private javax.swing.JButton cmdPreviousPage;
    private javax.swing.JButton cmdRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPage;
    private gui.tables.AccountsPayableTable table;
    // End of variables declaration//GEN-END:variables

    public AccountsPayableTable getTable() {
        return table;
    }



}
